version: '3.11'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example 

  flaskapp:
    build: ./flaskapp
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
